-- MySQL Script generated by MySQL Workbench
-- Thu Nov  7 10:55:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EconoMe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EconoMe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EconoMe` DEFAULT CHARACTER SET utf8 ;
USE `EconoMe` ;

-- -----------------------------------------------------
-- Table `EconoMe`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EconoMe`.`usuarios` (
  `id_u` INT NOT NULL AUTO_INCREMENT,
  `nombre_u` VARCHAR(255) NOT NULL,
  `apellido_u` VARCHAR(255) NOT NULL,
  `email_u` VARCHAR(255) NOT NULL,
  `password_u` VARCHAR(255) NOT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_u`),
  UNIQUE INDEX `email_u_UNIQUE` (`email_u` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EconoMe`.`categorias_gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EconoMe`.`categorias_gastos` (
  `id_cg` INT NOT NULL AUTO_INCREMENT,
  `categoria_cg` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EconoMe`.`gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EconoMe`.`gastos` (
  `id_g` INT NOT NULL AUTO_INCREMENT,
  `monto_g` DECIMAL(10,2) NOT NULL,
  `detalle_g` VARCHAR(255) NULL,
  `vencimiento_g` DATE NULL,
  `banco_g` VARCHAR(255) NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_u_g` INT NOT NULL,
  `id_categoria_g` INT NOT NULL,
  PRIMARY KEY (`id_g`),
  INDEX `fk_gastos_usuarios_idx` (`id_u_g` ASC) ,
  INDEX `fk_gastos_categorias_gastos1_idx` (`id_categoria_g` ASC) ,
  CONSTRAINT `fk_gastos_usuarios`
    FOREIGN KEY (`id_u_g`)
    REFERENCES `EconoMe`.`usuarios` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_categorias_gastos1`
    FOREIGN KEY (`id_categoria_g`)
    REFERENCES `EconoMe`.`categorias_gastos` (`id_cg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EconoMe`.`categorias_ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EconoMe`.`categorias_ingresos` (
  `id_ci` INT NOT NULL AUTO_INCREMENT,
  `categoria_i` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_ci`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EconoMe`.`ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EconoMe`.`ingresos` (
  `id_i` INT NOT NULL AUTO_INCREMENT,
  `monto_i` DECIMAL(10,2) NOT NULL,
  `id_usuario_i` INT NOT NULL,
  `id_categoria_i` INT NOT NULL,
  PRIMARY KEY (`id_i`),
  INDEX `fk_ingresos_usuarios1_idx` (`id_usuario_i` ASC) ,
  INDEX `fk_ingresos_categorias_ingresos1_idx` (`id_categoria_i` ASC) ,
  CONSTRAINT `fk_ingresos_usuarios1`
    FOREIGN KEY (`id_usuario_i`)
    REFERENCES `EconoMe`.`usuarios` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresos_categorias_ingresos1`
    FOREIGN KEY (`id_categoria_i`)
    REFERENCES `EconoMe`.`categorias_ingresos` (`id_ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EconoMe`.`cuenta_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EconoMe`.`cuenta_proyecto` (
  `id_cp` INT NOT NULL AUTO_INCREMENT,
  `objetivo_cp` DECIMAL(10,2) NOT NULL,
  `id_u_cp` INT NOT NULL,
  PRIMARY KEY (`id_cp`),
  INDEX `fk_cuenta_proyecto_usuarios1_idx` (`id_u_cp` ASC) ,
  CONSTRAINT `fk_cuenta_proyecto_usuarios1`
    FOREIGN KEY (`id_u_cp`)
    REFERENCES `EconoMe`.`usuarios` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EconoMe`.`ahorros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EconoMe`.`ahorros` (
  `id_a` INT NOT NULL AUTO_INCREMENT,
  `monto_a` DECIMAL(10,2) NOT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_u_a` INT NOT NULL,
  `id_cp_a` INT NOT NULL,
  PRIMARY KEY (`id_a`),
  INDEX `fk_ahorros_usuarios1_idx` (`id_u_a` ASC) ,
  INDEX `fk_ahorros_cuenta_proyecto1_idx` (`id_cp_a` ASC) ,
  CONSTRAINT `fk_ahorros_usuarios1`
    FOREIGN KEY (`id_u_a`)
    REFERENCES `EconoMe`.`usuarios` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ahorros_cuenta_proyecto1`
    FOREIGN KEY (`id_cp_a`)
    REFERENCES `EconoMe`.`cuenta_proyecto` (`id_cp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
